export const globeConfig = {
  worldView: { center: [-115, 24] as [number, number], zoom: 1.5 },
  introView: { center: [50, -18] as [number, number], zoom: 0.5 },
  zoom: { min: 0, max: 9.5, selectedPlace: 9.2, controlStep: 0.8, clusterExpansionOffset: 1 },
  padding: { desktopBottom: 138, mobileBottom: 92 },
  queries: { selectedPlace: "place" },
  memory: { storageKey: "kurtis.photo.globe.camera" },
  mediaQueries: {
    mobile: "(max-width: 780px)",
    reducedMotion: "(prefers-reduced-motion: reduce)",
  },
  animation: {
    selectedDuration: 1050,
    resetDuration: 850,
    introDuration: 6200,
    clusterDuration: 700,
    zoomDuration: 300,
  },
  lightingRefreshMs: 60_000,
  visibleHemisphereThreshold: 0.025,
  cluster: { maxZoom: 8, radius: 24 },
  style: {
    landOpacity: 0.98,
    countryBorderOpacity: [0, 0.78, 5, 0.9],
    countryBorderWidth: [0, 0.55, 5, 1.05],
    clusterRingRadius: [16, 8, 19, 20, 23],
    clusterRadius: [11, 8, 14, 20, 17],
    pinRadius: [0, 5.5, 4, 7.5, 9.5, 5.5],
    pinTouchRadius: 22,
    clusterBlur: 0.08,
    pinStrokeWidth: 2,
    clusterStrokeWidth: 1.5,
    selectedHaloRadius: 15,
    selectedHaloBlur: 0.12,
    selectedPinRadius: 9,
    selectedPinTouchRadius: 24,
    selectedPinStrokeWidth: 2.5,
    horizonBlend: 0.35,
    atmosphereBlend: [0, 0.32, 5, 0.08],
    lightRadius: 1.5,
    lightIntensity: 0.38,
  },
  colorTokens: {
    ocean: "--globe-ocean",
    land: "--globe-land",
    countryBorder: "--globe-country-border",
    pin: "--shell",
    selectedPin: "--ocean",
    paperBright: "--paper-bright",
    clusterRing: "--globe-cluster-ring",
    selectedHalo: "--globe-selected-halo",
    horizon: "--globe-horizon",
    sunlight: "--globe-sunlight",
  },
} as const;
