import { siteConfig } from "@/content/site-config";

export const siteCopy = {
  metadata: {
    description: "Travel, landscape, street, and portrait photography by Kurtis Schlepp.",
    socialDescription: "Things Kurtis saw along the way—travel, landscape, street, and portrait photography.",
    socialImageAlt: "kurtis.photo — photography by Kurtis Schlepp",
  },
  accessibility: {
    home: "kurtis.photo home",
    primaryNavigation: "Primary navigation",
    photoNavigation: "Photo navigation",
  },
  common: {
    previous: "← Previous",
    next: "Next →",
    photoNumber: (collectionTitle: string, order: number) => `${collectionTitle} No. ${String(order).padStart(siteConfig.countPadLength, "0")}`,
    allPhotographs: "All photographs",
    close: "Close",
    photographs: (count: number) => `${String(count).padStart(siteConfig.countPadLength, "0")} photographs`,
    coverAlt: (title: string) => `Cover photograph from ${title}`,
  },
  globe: {
    eyebrow: `${siteConfig.ownerName} · ${siteConfig.location}`,
    title: "Things I saw along the way.",
    introduction: "Travel, streets, and landscapes—organized by the places where I found them.",
    explore: "Explore places",
    collectionCount: (count: number) => `${String(count).padStart(siteConfig.countPadLength, "0")} collections`,
    places: "Places",
    shown: (count: number) => `${String(count).padStart(siteConfig.countPadLength, "0")} shown`,
    filterPlaceholder: "Filter the archive",
    surprise: "Surprise me",
    nearby: "Nearby in the archive",
    nearbyLabel: "Nearby places",
    placeListLabel: "Photography collections by place",
    noResults: "No places match that search.",
    photoIndex: "Photo index",
    inquiryLink: "Let’s take some photos",
    mapLabel: "Interactive globe of photography collections. Drag to rotate, pinch to zoom, or choose a place from the list.",
    loading: "Drawing the world…",
    unavailableEyebrow: "Map unavailable",
    unavailableTitle: "The archive is still open.",
    unavailableBody: "This browser could not render the globe. Choose any place from the list or open the photo index.",
    browse: "Browse photographs",
    controlsLabel: "Globe controls",
    zoomIn: "Zoom in",
    zoomOut: "Zoom out",
    reset: "Reset",
    selectedPlace: "Selected place",
    selectedFallback: (count: number) => `${count} photographs from this place.`,
    openCollection: "Open collection",
    openCollectionLabel: (title: string) => `Open ${title} collection`,
    closeSelected: "Close selected place",
    instructionsEyebrow: "The archive, geographically",
    instructions: "Drag to rotate. Select a pin or choose a place from the list.",
    instructionsDetail: "Larger pins group nearby places—select one to zoom in. Scroll or pinch to zoom.",
    mapError: "Globe map error",
    startError: "Globe map could not start",
  },
  places: {
    metadataTitle: "Places",
    eyebrow: "The archive",
    title: "Places",
    exploreGlobe: "Explore the globe",
    showOnGlobe: "See it on the globe",
    archiveEyebrow: "Alphabetical archive",
    archiveTitle: "All places",
    published: (count: number) => `${String(count).padStart(siteConfig.countPadLength, "0")} currently published`,
    metadataDescription: (location: string) => `Photographs made in ${location} by ${siteConfig.ownerName}.`,
    collectionFallback: (location: string) => `A collection of photographs made in ${location}.`,
    photoDescription: (location: string) => `${location} — a photograph by ${siteConfig.ownerName}.`,
  },
  portraits: {
    metadataTitle: "Portraits",
    sessionEyebrow: "Portrait session",
    metadataDescription: `Portrait photographs by ${siteConfig.ownerName}.`,
    sessionFallback: `A portrait session by ${siteConfig.ownerName}.`,
    heroEyebrow: "Portraits by Kurtis",
    heroTitle: "People, as they are.",
    heroBody: "Individuals, couples, families, engagements, proposals, and headshots.",
    heroAction: "Let’s take some photos",
    sessionTypesEyebrow: "Ways to be photographed",
    sessionTypesTitle: "A session shaped around you.",
    sessionTypesBody: "No fixed formula or required way to show up. We’ll choose the place, pace, and feeling together.",
    sessionGroups: [
      {
        number: "01",
        title: "Just you",
        types: "Individuals · Headshots",
        body: "Relaxed portraits with room for your personality, whether you need something polished or simply want to mark this version of yourself.",
      },
      {
        number: "02",
        title: "Together",
        types: "Couples · Engagements · Proposals",
        body: "A walk, an afternoon, or a carefully planned surprise—photographed without making it feel like a performance.",
      },
      {
        number: "03",
        title: "Family life",
        types: "Families · Maternity · Newborn",
        body: "The loud, tender, fleeting parts of growing a family, with plenty of space for everyone to be themselves.",
      },
    ],
    viewSession: (title: string) => `View ${title} portrait session`,
    viewSessionShort: "View session",
    portraitAlt: (title: string) => `Portrait from ${title}`,
    recentEyebrow: "Selected sessions",
    archiveTitle: "A few people I’ve had the pleasure to photograph.",
    archiveBody: "Each session is edited with its own pace, light, and place in mind.",
    processEyebrow: "How it works",
    processTitle: "Start with a note.",
    processBody: "Tell me what you’re picturing, where it might happen, and the pace you want. Every session is quoted individually.",
    processAction: "Tell me what you have in mind",
    locationEyebrow: "Based in San Diego",
    locationTitle: "Available across the county.",
    locationBody: "Have something farther away in mind? I’m happy to travel; additional travel costs may apply.",
    backTo: (title: string) => `← Back to ${title}`,
  },
  about: {
    metadataTitle: "About",
    eyebrow: "About Kurtis",
    title: "Trying to hold on to how a moment felt.",
    story: [
      "My wife’s photography made me want to try making some photographs of my own. Since then, the camera has become a way of carrying a trip home with me.",
      "When I go back through a set of photos, I want to feel pulled right back into the moment. The excitement of being somewhere new, that first vacation beer, trying the local street food for the first time.",
      "I’m Kurtis Schlepp, a photographer and software engineer based in San Diego. This is a growing collection of the places and people I’ve been lucky enough to spend time with.",
    ],
    photoAlt: "Kurtis and his wife smiling together",
    photoCaption: "Me and my wife, Ashley.",
    contactEyebrow: "Say hello",
    instagramLabel: "Instagram:",
    instagramStatus: "coming soon",
  },
  inquiry: {
    metadataTitle: "Let’s take some photos",
    eyebrow: "Portrait inquiry",
    title: "Let’s take some photos.",
    directEmail: `Or email me directly at ${siteConfig.email}`,
    error: "Your note could not be sent.",
    successEyebrow: "Message received",
    successTitle: "Thanks for reaching out.",
    successBody: "I got your note and will be in touch soon. —Kurtis",
    fields: {
      website: "Website",
      name: "Name",
      email: "Email",
      shootType: "What are you planning?",
      shootTypePlaceholder: "Choose one",
      date: "Ideal date or timeframe",
      datePlaceholder: "Whenever the light is right",
      location: "Location",
      locationPlaceholder: "San Diego, or somewhere farther",
      budget: "Approximate budget",
      budgetPlaceholder: "Optional",
      message: "Tell me more",
      consent: "I’m happy for Kurtis to use this information to respond to my photography request.",
    },
    sending: "Sending…",
    submit: "Send inquiry",
  },
  prints: {
    metadataTitle: "Prints",
    confirmationEyebrow: "Order received",
    confirmationTitle: "Thanks for bringing a moment home.",
    confirmationBody: "Your payment went through, and I’ll get your print ready. It’s made to order and usually ships within 7–14 business days. I’ll follow up by email if anything needs your attention.",
    confirmationAction: "Keep exploring",
    verificationEyebrow: "Checkout status",
    verificationTitle: "Your payment is still being confirmed.",
    verificationBody: `Your cart has been kept intact. If Stripe charged you and this message remains, email ${siteConfig.email} with the receipt and I’ll take care of it.`,
    eyebrow: "Prints",
    title: "A few photographs for the wall.",
    introduction: "Available occasionally, selected from the places and moments that have stayed with me.",
    emptyEyebrow: "For now",
    emptyTitle: "Nothing is for sale right now.",
    emptyBody: "I’m keeping this collection small on purpose. A few photographs will appear here when the moment feels right.",
    emptyAction: "Explore the archive",
    availableLabel: "Available prints",
    enlargeLabel: (title: string) => `Enlarge ${title}`,
    photoCount: (count: number) => `${count} ${count === 1 ? "photograph" : "photographs"}`,
    originalCollection: "View original collection",
  },
  printInfo: {
    metadataTitle: "Print info",
    eyebrow: "Print details",
    title: "Made to spend time with.",
    introduction: "Photographs offered through the Prints page are unframed lustre prints. Kurtis signs the back by hand with the photograph’s location and year.",
    pricingEyebrow: "Sizes & pricing",
    pricingTitle: "Chosen to respect the photograph.",
    pricingBody: "Each print only offers sizes that preserve its original composition. Panoramas may include a white border so nothing is cropped.",
    fulfillmentEyebrow: "Fulfillment",
    fulfillmentTitle: "A few practical details.",
    fulfillmentDetails: [
      "U.S. shipping only, calculated at checkout.",
      "Made to order; please allow 7–14 business days before shipment.",
      "Replacements for damaged or incorrect orders. Made-to-order prints are otherwise final sale.",
      `Questions before ordering? Email ${siteConfig.email}.`,
    ],
  },
  cart: {
    providerError: "Cart components must be used inside CartProvider.",
    toggle: "Cart",
    itemCount: (count: number) => `${count} items`,
    printSize: "Print size",
    add: "Add print",
    printNote: "Signed, unframed lustre print. Full composition preserved; borders may be added for panoramic ratios.",
    checkoutError: "Checkout could not start.",
    label: "Shopping cart",
    eyebrow: "Your selections",
    title: "Cart",
    close: "Close",
    empty: "Nothing in your cart yet. Prints are available from each photograph.",
    decrease: "Decrease quantity",
    increase: "Increase quantity",
    remove: "Remove",
    subtotal: "Print subtotal",
    footnote: "U.S. shipping and applicable tax are calculated at checkout. Fulfillment typically takes 7–14 business days.",
    openingCheckout: "Opening checkout…",
    checkout: "Checkout",
  },
  gallery: {
    close: "Close",
    previousLabel: "Previous photograph",
    nextLabel: "Next photograph",
  },
  legal: {
    privacy: {
      metadataTitle: "Privacy",
      eyebrow: "Privacy",
      title: "Privacy, in plain language.",
      paragraphs: [
        "kurtis.photo collects the information you submit through the portrait inquiry form—your name, email address, and project details—only to respond to your request. It is not sold or used for marketing lists.",
        "Checkout information is collected and processed by Stripe. This site uses privacy-focused Cloudflare Web Analytics to understand aggregate page and photo views; it does not build visitor profiles.",
        `Questions about privacy can be sent to ${siteConfig.email}.`,
      ],
    },
    terms: {
      metadataTitle: "Terms",
      eyebrow: "Terms",
      title: "A few ground rules.",
      paragraphs: [
        "All photographs on kurtis.photo are copyrighted by Kurtis Schlepp. Website images are provided for viewing and sharing through their original links, not for downloading, reproduction, or commercial use without permission.",
        "Print orders are made to order. Pricing, availability, and compatible print sizes may change as the archive grows. Shipping is currently limited to the United States.",
        "Portrait pricing and project details are confirmed individually before work begins.",
      ],
    },
  },
  footer: {
    copyright: (year: number) => `© ${year} ${siteConfig.ownerName}`,
    privacy: "Privacy",
    terms: "Terms",
  },
} as const;
